"""Initial migration.

Revision ID: d0c7b8e4b57c
Revises: 
Create Date: 2022-11-08 17:00:02.151921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0c7b8e4b57c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bikes',
    sa.Column('bike', sa.String(), autoincrement=True, nullable=False),
    sa.Column('km_stand', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bike')
    )
    op.create_table('wetter',
    sa.Column('bedingung', sa.String(), nullable=False),
    sa.Column('faktor', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('bedingung')
    )
    op.create_table('fahrten',
    sa.Column('fahrt_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bike', sa.String(), nullable=True),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('strecke', sa.Integer(), nullable=True),
    sa.Column('wetter', sa.String(), nullable=True),
    sa.Column('strava_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bike'], ['bikes.bike'], ),
    sa.PrimaryKeyConstraint('fahrt_id')
    )
    op.create_table('wartung',
    sa.Column('wartung_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=True),
    sa.Column('bike', sa.String(), nullable=True),
    sa.Column('service', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['bike'], ['bikes.bike'], ),
    sa.PrimaryKeyConstraint('wartung_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wartung')
    op.drop_table('fahrten')
    op.drop_table('wetter')
    op.drop_table('bikes')
    # ### end Alembic commands ###
